// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.Models;

public partial class Cliente
{
    public int PKCLIENTE { get; set; }

    public string CEDULA { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO1 { get; set; }

    public string APELLIDO2 { get; set; }
}